language: csharp
mono:
  - latest
  - 4.2.1
cache:
  - apt
env:
  global:
    - secure: Kvx8WFKF8TnLeaJryJPajfQcIPdWu0sPpx06iuZWIPaql/WUTTd5BjgsiyWAk3V0hF/kgwy6SbI6QBhFpIWl9LwbJiua/pCwIhTZy68BZBqFtVil39adaezNa9HY0G2jp0aHFmFNZfMmVjSUcrIpXqykeTtdBz9cpmVR0VtntdRgY0lYJvBLUxNLoNZXsQURWYousq/kTgq7KSBawCEpFz1uXim5EWXPhPpXd7ogO5lReBmBJ2/0awi+6EheKjFrnUDFR/A5P8OQMpVWuZ8zv2wP1BJ/eqcNnO+RhvBnEZqp3bsinT8JMP16WjQh5SIp2VJhiMCYev/DwrmbO645tJpSm3phWZ7f9E9NOTUPL2frGjHBGKVOyb59yxoIRwGdd45qXTyRDJ3d6o5gDW4evp3M7AD9DO+bldgm6XnyQFJgS6/cl3HMV3WRCBDOsUxm+ws+OF8+slyX9seST3GYPOxz/z9iiMlEQA6vnXEbPsZntqGCRn4PNIM3lnpuqmhboSSbjino90DRnncvPAI+GzAu25f4l+mY+ycfV4E3A1mDp5GRlKl6wNiKVI3VNznRSGjcEcOVFMgVNvfkIY8nIGUAUQMiouZNnjmSXufu/X/a4gVweSe09ezoNmW5YrhYSi9YJBVceFDgXgxjco/248SGcc64KXs4fx94A+hjcXU=
    - secure: b7SSnXSB9GhfYOF4x98GeDnFOREpJUuYjAlildHASA+Zeel7RMDskUD7akid6i4iPqnZi72WMbk7LXeZwmtY0a3F39K/1/0YS50JqNQRBX791yn425k1wTGL+hvLclVJLjfrvjy5KJr01TPwzffkC7xnHF/Vtw2ok3MpunpgrCCXhKS1dFEI8WhOyPLNyCcrHWM5OiZ9gOG+NmNEwAJ5VnOcFmBJSJJnubYH7tfg4+LA0OcMKi4umuYvNESa0qaoKM+LLaHm1YiITKHHR1nht90PXyx5pU2UNE6xovmVQngGNtfaeVcwUYav8DwAg9WvQqvHy4zC6X1kBgMF+pbIIDtU3uxgc66fWHCnrZ6bA0w8VBdu6pZJc6hywQOTOrlUPyaotqo+odo6Tddo3DdTCWtBMgnLTniWMcRA0LZgeoEJqyXJJHd3S1paBz66I3Lo5hLWyrK539cAbwimkYNbdgXpsZeKaIc0vYuJjzhT01Dn6F64kpDe/UHhbokNjadphd1/kmyZnAgKyhnaxLqGVodqIU9YY/59vnu/bvX8vP0KiiGh/Es7P7EfkOkjgg2m1qVb1rVJHmxQF0KSTmzhjbmnWqa28wmX+fv8mZaZ2+k/tHCbW0zPd08U8PLgiSRz9Jt6prunCOYJeVV0EGALGTZravMqW+pQ5jY8bGf03oU=
# These commands simulate having a graphical display, which is needed
# for our GUI tests.
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - sudo apt-get install mono-devel nunit-console libtest-most-perl libipc-system-simple-perl
  - mozroots --import --ask-remove
script:
  - bin/build
  - nunit-console --exclude=FlakyNetwork build/Tests/bin/Debug/CKAN.Tests.dll
  - prove # Run all the tests in t/
deploy:
  -
    provider: releases
    api_key:
      secure: U0dSGTYvxQlRPRFZMpo4TJju5xN70aeUt6ZRdMVUhY6OndBvZ+Q/Km/veo23uON/dx8LsluxqwQPNqsWEDUVna9v/l03YHhLJwxOOiXaQnmLVuOIFpipWYaHiH3tSNQrR/isXImRR6BkpUw2h499ctWXe8btZGPeh9o8sn6FxvVJ584nxDhzkCSMKmGGQHGjK5hkzBW7IbwWrak+McQdryUuQMfPUkeQjbCpVqhntd3byH2M9/fSRyDYLvse0eaSLilVfr+x+aKyNnPWkyzKMuMf/aX7pdXD8lZbKx5jA0RL9/7BeNQiM0gmBIl85w7BHGkI3t7vbrgljteJQJbT9xUhJzicb6YHT36RRXmAmPrWwkImVv9iLf3dsp/EPZYRn+D9EbkZJaSVn0G0yNGXRj2Q/z+1B/wdemhiSNgDBTF1O5qjv3BLGxd8Qzha4Znol21JbbvhbNgfLSv56FAfFhXkA0hOHN7mNxxScMB5ZKscZ25OEO7Fly8Zlimwe7/bjjwb/8WTeLCliThZZOYBa1DxPDCzS5KVHCE4OX3YodjvpU5uA9LOHX5jaVVjojzIYink4TlvTsxIkicpnqKDxZZWLivjLwzPoimf7D0a3jKguxHWoUGFnnCchV2EWfwLzP2lWDSHKsxXWzLe0yV6uBEa05S/spB2/FDaInIusy8=
    file:
      - build/cfan.exe
      - build/cfan_headless.exe
      - build/cfan_netfan.exe
      - build/cfan_updater.exe
    skip_cleanup: true
    on:
      repo: trakos/CFAN
      tags: true
      condition: $(mono --version | perl -ne'/version (\S+)/ and print $1') = 4.2.1
  -
    provider: script
    script: bin/webdav_deploy.sh
    skip_cleanup: true
    on:
      repo: trakos/CFAN
      condition: $(mono --version | perl -ne'/version (\S+)/ and print $1') = 4.2.1
      all_branches: true