language: csharp
mono:
  - latest
  - 5.12.0
cache:
  - apt
env:
  global:
    - secure: RyCIbzmci/2RbYx8aDvbabQWsqyBILUsXPYQ/GSjBS2qkwj7xAfd65jGERJWVTplXzq81WXIq1TQiJgN+5L+XriCcBrYyJ5rlDdE9AMPg0iPbIWLBo7jikUGzB3W4M33Xzr4zmIJ2kxpGycWrWjIXA5RHQH0/BBS1qnV6QkBjabmN5IiRuOrem2r5909lT5Cr2dAvbW9pLhe04LgwjUcM+11U6iJhqgDHVSABp3/qfe1wkZSdIDvpGG5CGGZyDtfd1QgUl5u8hKgZk6nn0Goh4fX3/j0y+MigrfJ5hKPD30t/4jC/w40PvRnTRY13KR6x7cWEEinQjwlOy5pnWxjtnHJSaTRQez2V4JlXSTx71P82eV+5IWu6L83TE49FHjBvp5TQiSppEl39ie5GSk568A4GS3pp52xHlm1uAkCXrgspbZuV2HmFl38dC2CkMnBUJdxfZkFl5BcBdH9IjrHYfkP71WfcRzcwSNDyAM0aRmcbhYNRmrrHN4/gUR0nFgj6Qnt7m1xjo14BnCCRjKcm3zali7ltvCR2FrEDp4oDQsebwY9WNXiHALEoMPfEVFlYdr+pTI3d6J7Tb2qtpc+Jl98Acg5VNj1EwFNquBJBRrjZ4QtKrMutXLsSgVAxfNV0+K86hIZEqwTASNiacMTC6VD0JOElwvvMGDe+eAivoI=
    - secure: BFnSKrZnCsaV6bc/Lp/IVrMclSL/Heikf+QH2YbChdMX66NcQFbSJxpWSMDsBpXa0er7j2gZeqDUFtwMwQJ07JVNhj/vIwXv56AgDRg7LGO8TBGVqTrRKmr+9MnFUnOBGP2juXsBjqP5DFWvH+BMwy7jV0m6ua95P5O9QjTWrq/LI5uwMMlUXOoXKFbicEaCpeOHcRD+nIhgyO0fe+uChryDidCi/Ng2O+6VOAS1TetiI0cIrnlDhlUubZKHli6BOVDgch65/xOKZt7qkuIThEJZAfQByq14CnkT2NpGhqEFHeWyT3N571jpnVxlPHrjXK4EEzCE9ZgUZOpkNIqmTpG77huZNO6NjO7MP8CvF9Z5sTVmpM197zl7SxLbMSBO1Yy8z3JbXJtY+2Y9GzUBH36j3vESYsZ2x3attB/1V75xkH3DOy4fyKZptw3UkPvaKlIWjmLj4CW+6IPdWraEltJDRsRGcMrnwZfufjV4IW82L6ay+rQd1zWp7kBVZE+yLoPzopIDs5A6C8Iq8EFtOBp5sRnUfWRatlzIAePlRjO0nv1JDeu5PDni/kvIXNI91oHeozJbnOkgfSNJe1hWPaZActZYhwTDbiS4YqFefko50U0f+9cpDnC0RD0NymKSmogQNeIGVft4Xo9FiagSewYT0ZpgQkyv2Fdqv1UvT6g=
services:
  - xvfb
before_install:
  - export DISPLAY=:99.0
install:
  - sudo apt-get install mono-devel nunit-console libtest-most-perl libipc-system-simple-perl
script:
  - bin/build
  - nunit-console --exclude=FlakyNetwork build/Tests/bin/Debug/CKAN.Tests.dll
  - chmod ugo+x build/*.exe
  - prove # Run all the tests in t/
deploy:
  -
    provider: releases
    api_key:
      secure: U0dSGTYvxQlRPRFZMpo4TJju5xN70aeUt6ZRdMVUhY6OndBvZ+Q/Km/veo23uON/dx8LsluxqwQPNqsWEDUVna9v/l03YHhLJwxOOiXaQnmLVuOIFpipWYaHiH3tSNQrR/isXImRR6BkpUw2h499ctWXe8btZGPeh9o8sn6FxvVJ584nxDhzkCSMKmGGQHGjK5hkzBW7IbwWrak+McQdryUuQMfPUkeQjbCpVqhntd3byH2M9/fSRyDYLvse0eaSLilVfr+x+aKyNnPWkyzKMuMf/aX7pdXD8lZbKx5jA0RL9/7BeNQiM0gmBIl85w7BHGkI3t7vbrgljteJQJbT9xUhJzicb6YHT36RRXmAmPrWwkImVv9iLf3dsp/EPZYRn+D9EbkZJaSVn0G0yNGXRj2Q/z+1B/wdemhiSNgDBTF1O5qjv3BLGxd8Qzha4Znol21JbbvhbNgfLSv56FAfFhXkA0hOHN7mNxxScMB5ZKscZ25OEO7Fly8Zlimwe7/bjjwb/8WTeLCliThZZOYBa1DxPDCzS5KVHCE4OX3YodjvpU5uA9LOHX5jaVVjojzIYink4TlvTsxIkicpnqKDxZZWLivjLwzPoimf7D0a3jKguxHWoUGFnnCchV2EWfwLzP2lWDSHKsxXWzLe0yV6uBEa05S/spB2/FDaInIusy8=
    file:
      - build/cfan.exe
      - build/cfan_headless.exe
      - build/cfan_netfan.exe
      - build/cfan_updater.exe
    skip_cleanup: true
    on:
      repo: trakos/CFAN
      tags: true
      condition: $(mono --version | perl -ne'/version (\S+)/ and print $1' | head -c 6) = 5.12.0
  - 
    provider: script
    script: bin/webdav_deploy.sh
    skip_cleanup: true
    on:
      repo: trakos/CFAN
      condition: $(mono --version | perl -ne'/version (\S+)/ and print $1' | head -c 6) = 5.12.0
      all_branches: true
